---
image:
    file: .gitpod/Dockerfile
    context: .gitpod
# checkoutLocation: gopherbot
# workspaceLocation: gopherbot
tasks:
- init: make
- init: ./.gitpod/gotools.sh
- command: ./.gitpod/setup.sh
  openIn: main
ports:
- port: 8080
  onOpen: ignore
