---
image:
    file: .gitpod/Dockerfile
    context: .gitpod
checkoutLocation: gopherbot
workspaceLocation: .
tasks:
- command: make -C gopherbot
- init: ./gopherbot/.gitpod/clone-robot.sh
  openIn: main
ports:
- port: 8080
  onOpen: ignore