#!/bin/bash -e

# Trivial EXECUTABLE to Gopherbot EXECUTABLEs in to $PATH

DEST="$1"

if [ ! "$DEST" ]
then
    echo "Missing required <dest-dir>"
    exit 1
fi

if [ ! -d "$DEST" ]
then
    echo "Not a directory: $DEST"j
    exit 1
fi

if [ ! -w "$DEST" ]
then
    echo "Destination not writable: $DEST"
    exit 1
fi

EXECUTABLE_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

for EXECUTABLE in gopherbot cbot privsep
do
    ln -snf "$EXECUTABLE_DIR/$EXECUTABLE" "$DEST"
done
echo "linked"