# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
[prune]
  unused-packages = true

# NOTE: Only until the next release includes the bugfix
[[constraint]]
  name = "github.com/nlopes/slack"
  revision = "921a31ba7374bbc3623a5327e1f965628d1d6108"
  
# NOTE: The current release is pretty old, and doesn't
# include some important bugfixes
[[constraint]]
  name = "github.com/chzyer/readline"
  revision = "f6d7a1f6fbf35bbf9beb80dc63c56a29dcfb759f"

[[constraint]]
  branch = "master"
  name = "github.com/duosecurity/duo_api_golang"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"
