FROM quay.io/lnxjedi/gopherbot-base:latest

ARG username=robot
ARG userid=1000
ARG nonprivuser=nobody

ARG installdir=/opt
ARG homedir=/home/robot

ENV HOME=${homedir}
ENV GOPATH=${HOME}
ENV PATH=${HOME}/go/bin:${HOME}/.local/bin:/opt/gopherbot:${PATH}
ENV USER=${username}
ENV USERID=${userid}

ARG buildref
ENV BUILDREF=${buildref}

RUN useradd -d ${homedir} -m -u ${userid} ${username} && \
  cd / && \
  [ "$BUILDREF" ] && CLONEREF="-b $BUILDREF" || : && \
  git clone ${CLONEREF} https://github.com/lnxjedi/gopherbot.git build && \
  cd build && \
  make dist && \
  rm -rf ${HOME}/.cache && \
  cd ${installdir} && \
  tar xzf /build/gopherbot-linux-amd64.tar.gz && \
  rm -rf /build && \
  chown ${nonprivuser}:${username} ${installdir}/gopherbot/gopherbot && \
  chmod u+s ${installdir}/gopherbot/gopherbot && \
  chmod go+rx ${HOME}

WORKDIR ${HOME}
USER ${userid}:${USER}

ENTRYPOINT [ "/opt/gopherbot/gopherbot" , "-plainlog" ]
