FROM quay.io/lnxjedi/gopherbot-base-theia:latest

USER root

ADD gopherbot-linux-amd64.tar.gz /opt

RUN chown nobody /opt/gopherbot/gopherbot && \
  chmod u+s /opt/gopherbot/gopherbot

# Tiny little init
RUN cd / && \
  curl -s -L -o dinit \
    $(curl --silent https://api.github.com/repos/lnxjedi/dinit/releases/latest | jq -r .assets[0].browser_download_url) && \
  chmod 755 dinit

# Numeric for Kubernetes runAsNonRoot
USER ${ROBOT_UID}:${ROBOT_UID}

EXPOSE 3000
ENTRYPOINT [ "/dinit", "-r", "ssh-agent", "node", "/usr/local/theia/src-gen/backend/main.js", "/var/lib/robot", "--hostname=0.0.0.0" ]
