// Code generated by "stringer -type=LogLevel botdefs.go"; DO NOT EDIT.

package robot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Trace-0]
	_ = x[Debug-1]
	_ = x[Info-2]
	_ = x[Audit-3]
	_ = x[Warn-4]
	_ = x[Error-5]
	_ = x[Fatal-6]
}

const _LogLevel_name = "TraceDebugInfoAuditWarnErrorFatal"

var _LogLevel_index = [...]uint8{0, 5, 10, 14, 19, 23, 28, 33}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
