// Code generated by "stringer -type=Protocol connector_defs.go"; DO NOT EDIT.

package robot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Slack-0]
	_ = x[GoogleChat-1]
	_ = x[Rocket-2]
	_ = x[Terminal-3]
	_ = x[Test-4]
	_ = x[Null-5]
	_ = x[SSH-6]
}

const _Protocol_name = "SlackGoogleChatRocketTerminalTestNullSSH"

var _Protocol_index = [...]uint8{0, 5, 15, 21, 29, 33, 37, 40}

func (i Protocol) String() string {
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
