// Code generated by "stringer -type=Protocol botdefs.go"; DO NOT EDIT.

package robot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Slack-0]
	_ = x[Rocket-1]
	_ = x[Terminal-2]
	_ = x[Test-3]
}

const _Protocol_name = "SlackRocketTerminalTest"

var _Protocol_index = [...]uint8{0, 5, 11, 19, 23}

func (i Protocol) String() string {
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
