// Code generated by "stringer -type=RetVal robot_constants.go"; DO NOT EDIT.

package robot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-0]
	_ = x[UserNotFound-1]
	_ = x[ChannelNotFound-2]
	_ = x[AttributeNotFound-3]
	_ = x[FailedMessageSend-4]
	_ = x[FailedChannelJoin-5]
	_ = x[DatumNotFound-6]
	_ = x[DatumLockExpired-7]
	_ = x[DataFormatError-8]
	_ = x[BrainFailed-9]
	_ = x[InvalidDatumKey-10]
	_ = x[InvalidConfigPointer-11]
	_ = x[ConfigUnmarshalError-12]
	_ = x[NoConfigFound-13]
	_ = x[RetryPrompt-14]
	_ = x[ReplyNotMatched-15]
	_ = x[UseDefaultValue-16]
	_ = x[TimeoutExpired-17]
	_ = x[Interrupted-18]
	_ = x[MatcherNotFound-19]
	_ = x[NoUserEmail-20]
	_ = x[NoBotEmail-21]
	_ = x[MailError-22]
	_ = x[TaskNotFound-23]
	_ = x[MissingArguments-24]
	_ = x[InvalidStage-25]
	_ = x[InvalidTaskType-26]
	_ = x[CommandNotMatched-27]
	_ = x[TaskDisabled-28]
	_ = x[PrivilegeViolation-29]
}

const _RetVal_name = "OkUserNotFoundChannelNotFoundAttributeNotFoundFailedMessageSendFailedChannelJoinDatumNotFoundDatumLockExpiredDataFormatErrorBrainFailedInvalidDatumKeyInvalidConfigPointerConfigUnmarshalErrorNoConfigFoundRetryPromptReplyNotMatchedUseDefaultValueTimeoutExpiredInterruptedMatcherNotFoundNoUserEmailNoBotEmailMailErrorTaskNotFoundMissingArgumentsInvalidStageInvalidTaskTypeCommandNotMatchedTaskDisabledPrivilegeViolation"

var _RetVal_index = [...]uint16{0, 2, 14, 29, 46, 63, 80, 93, 109, 124, 135, 150, 170, 190, 203, 214, 229, 244, 258, 269, 284, 295, 305, 314, 326, 342, 354, 369, 386, 398, 416}

func (i RetVal) String() string {
	if i < 0 || i >= RetVal(len(_RetVal_index)-1) {
		return "RetVal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RetVal_name[_RetVal_index[i]:_RetVal_index[i+1]]
}
