FROM quay.io/lnxjedi/gopherbot-theia:latest

ARG username=robot
ARG userid=1000
ARG nonprivuser=nobody

ARG installdir=/opt
ARG homedir=/home/robot

WORKDIR /usr/local/theia
USER ${userid}:${GROUP}

ENTRYPOINT [ "node", "/usr/local/theia/src-gen/backend/main.js", "${homedir}", "--hostname=0.0.0.0" ]
