FROM quay.io/lnxjedi/gopherbot-base-theia:latest

ARG username=robot
ARG userid=1000
ARG nonprivuser=nobody

ARG installdir=/opt

# For dev
ADD gopherbot.tar.gz ${installdir}
RUN chown ${nonprivuser}:${username} ${installdir}/gopherbot/gopherbot && \
  chmod u+s ${installdir}/gopherbot/gopherbot && \
  ln -s ${installdir}/gopherbot/gopherbot ${HOME}/gopherbot && \
  ln -s ${installdir} ${HOME}/defaults && \
  chown -R robot:robot ${HOME} && \
  chmod go+rx ${HOME}

WORKDIR /usr/local/theia
USER ${userid}:${GROUP}

# NOTE: the entrypoint is hard-coded to /home/robot to work around a bug; TODO: proper fix using
# ${homedir} or ${HOME}.
ENTRYPOINT [ "node", "/usr/local/theia/src-gen/backend/main.js", "/home/robot", "--hostname=0.0.0.0" ]
