FROM quay.io/lnxjedi/gopherbot-theia:latest

USER root

# Tiny little init
RUN cd / && \
  git clone https://github.com/lnxjedi/dinit.git build && \
  cd build && \
  make && \
  mv dinit / && \
  cd / && \
  rm -rf /build /root/.cache

# Numeric for Kubernetes runAsNonRoot
USER 1000:robot

WORKDIR /usr/local/theia

EXPOSE 3000
ENTRYPOINT [ "/dinit", "-r", "ssh-agent", "node", "/usr/local/theia/src-gen/backend/main.js", "/home/robot", "--hostname=0.0.0.0" ]
