FROM quay.io/lnxjedi/gopherbot-base:latest

USER root

ADD gopherbot-linux-amd64.tar.gz /opt

RUN chown nobody /opt/gopherbot/gopherbot && \
  chmod u+s /opt/gopherbot/gopherbot

# Numeric for Kubernetes runAsNonRoot
USER ${ROBOT_UID}:${ROBOT_UID}

ENTRYPOINT [ "/opt/gopherbot/gopherbot" , "-plainlog" ]
