#!/usr/bin/ruby

# boilerplate
require ENV["GOPHER_INSTALLDIR"] + '/lib/rubylib'

bot = Robot.new()
# /boilerplate

=begin
The defaultConfig is a multi-line YAML formatted document that specifies
this plugins default configuration for Gopherbot. It may include any of the
fields in https://godoc.org/github.com/parsley42/gopherbot/bot#Plugin, as
well as arbitrary YAML for config data that a bot admin might want to
override.
=end
defaultConfig = <<'DEFCONFIG'
Channels: [ "botdev", "random" ]
Help:
- Keywords: [ "ruby" ]
  Helptext: [ "(bot), ruby( me!) - prove that ruby plugins work" ]
CommandMatches:
- Regex: (?i:ruby( me)?!?)
  Command: ruby
Config:
  Replies:
  - "Consider yourself rubied"
  - "Waaaaaait a second... what do you mean by that?"
  - "Ok, I will, but not right now - I'll wait 'til you're least expecting it..."
  - "Crap, all out of rubies - here's an emerald"
DEFCONFIG

command = ARGV[0]

case command
when "configure"
	puts defaultConfig
	exit
when "ruby"
	bot.Say("You've been rubied, #{bot.GetSenderAttribute("firstName")}")
end
