package suites

import "github.com/lnxjedi/gopherbot/v2/bot"

func init() {
	Register(Suite{
		Name:      "TestLists",
		ConfigDir: "test/membrain",
		LogName:   "bottest.log",
		Cases: legacyCases([]testItem{
			{aliceID, general, ";list lists", false, []TestMessage{{null, general, "I don't have any lists", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, ";add burgers to the meals list", false, []TestMessage{{alice, general, "I don't have a .*", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{bobID, random, ";add burgers to the meals list", false, []TestMessage{{bob, random, "I don't have a .*", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{bobID, random, "yes", false, []TestMessage{{null, random, "Ok, I created a new meals list and added burgers to it", false}}, []bot.Event{}, 0},
			{aliceID, general, "yes", false, []TestMessage{{null, general, "Somebody already created the meals list and added burgers to it", false}}, []bot.Event{}, 0},
			{aliceID, general, ";add eggs to the Breakfast list", false, []TestMessage{{alice, general, "I don't have .*", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{bobID, random, ";add bacon to the breakfast list", false, []TestMessage{{bob, random, "I don't have a .*", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{bobID, random, "yes", false, []TestMessage{{null, random, "Ok, I created a new breakfast list and added bacon to it", false}}, []bot.Event{}, 0},
			{aliceID, general, "yes", false, []TestMessage{{null, general, "Ok, I added eggs to the new Breakfast list", false}}, []bot.Event{}, 0},
			{aliceID, general, ";show the meals list", false, []TestMessage{{null, general, `(?m:Here's what I have.*\nburgers$)`, false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{carolID, general, ";remove BURGERS from the meals list", false, []TestMessage{{null, general, "Ok, I removed BURGERS from the meals list", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{carolID, general, ";show the list", false, []TestMessage{{null, general, "The meals list is empty", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{carolID, general, ";delete the breakFAST list", false, []TestMessage{{null, general, "Deleted", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, ";list lists", false, []TestMessage{{null, general, `(?m:Here are the lists I know about:\nmeals)`, false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, ";show the MEALS list", false, []TestMessage{{null, general, "The MEALS list is empty", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
		}),
	})
	Register(Suite{
		Name:      "TestGroupAuth",
		ConfigDir: "test/membrain",
		LogName:   "bottest.log",
		Cases: legacyCases([]testItem{
			{aliceID, general, ";list groups", false, []TestMessage{{null, general, "Here are the groups.*", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan, bot.AdminCheckPassed}, 0},
			{aliceID, general, ";show the foo group", false, []TestMessage{{null, general, "I don't have a .*", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, ";show the Helpdesk group", false, []TestMessage{{null, general, "(?m:The Helpdesk group has the following members:\ncarol\nbob$)", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan, bot.AdminCheckPassed}, 0},
			{aliceID, general, ";remember The Alamo", false, []TestMessage{{null, general, "Sorry, you're not authorized for .*", false}}, []bot.Event{bot.GoPluginRan, bot.AdminCheckPassed, bot.AuthRanFail}, 0},
			{carolID, general, ";list groups", false, []TestMessage{{null, general, "(?m:Here are the groups you're an administrator for:\n.*\n.*$)", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan, bot.AdminCheckFailed}, 0},
			{bobID, general, ";remember Lieutenant Dan", false, []TestMessage{{null, general, "Ok, .*", false}}, []bot.Event{bot.GoPluginRan, bot.AdminCheckFailed, bot.AuthRanSuccess, bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{davidID, general, ";remember Forest Gump", false, []TestMessage{{null, general, "Sorry, you're not authorized for .*", false}}, []bot.Event{bot.GoPluginRan, bot.AdminCheckFailed, bot.AuthRanFail}, 0},
			{carolID, general, ";remember Forest Gump", false, []TestMessage{{null, general, "Ok, I'll remember .*", false}}, []bot.Event{bot.GoPluginRan, bot.AdminCheckFailed, bot.AuthRanSuccess, bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{carolID, general, ";add david to the Helpdesk group", false, []TestMessage{{null, general, "Ok, I added david to the Helpdesk group", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan, bot.AdminCheckFailed}, 0},
			{davidID, general, ";remember Jenny", false, []TestMessage{{null, general, "Ok, I'll remember .*", false}}, []bot.Event{bot.GoPluginRan, bot.AdminCheckFailed, bot.AuthRanSuccess, bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{aliceID, general, ";remove bob from the Helpdesk group", false, []TestMessage{{null, general, "bob isn't a dynamic member of the Helpdesk group", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan, bot.AdminCheckPassed}, 0},
		}),
	})
	Register(Suite{
		Name:      "TestMemory",
		ConfigDir: "test/membrain",
		LogName:   "bottest.log",
		Cases: legacyCases([]testItem{
			{carolID, random, ";remember slowly The Alamo", false, []TestMessage{{null, random, "Ok, .*", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{aliceID, random, ";remember Ferris Bueller", false, []TestMessage{{null, random, "Ok, .*", false}, {null, random, "committed to memory", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{bobID, random, "recall 1, Bender", false, []TestMessage{{null, random, "Ferris Bueller", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{carolID, random, ";remember Ferris Bueller", false, []TestMessage{{null, random, "That's already one of my fondest memories", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{davidID, random, "forget 1, Bender", false, []TestMessage{{null, random, "Ok, .*", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{davidID, general, "Bender, what is Ferris Bueller?", false, []TestMessage{{david, general, "Gosh, I have no idea .*", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{davidID, general, ";store Ferris Bueller is a Righteous Dude", false, []TestMessage{{null, general, "I'll remember .*", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{davidID, general, "Bender, what is Ferris Bueller?", false, []TestMessage{{null, general, "Ferris Bueller is a Righteous Dude", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{carolID, general, "Bender, what is Ferris Bueller?", false, []TestMessage{{carol, general, "Gosh, I have no idea .*", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{davidID, random, "Bender, what is Ferris Bueller?", false, []TestMessage{{david, random, "Gosh, I have no idea .*", false}}, []bot.Event{bot.CommandTaskRan, bot.ExternalTaskRan}, 0},
			{bobID, general, "Bender, link news for nerds to https://slashdot.org", false, []TestMessage{{null, general, "Link added", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{bobID, general, ";save https://slashdot.org", false, []TestMessage{{null, general, "I already have that link", false}, {bob, general, "Do you want .*", false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{bobID, general, "yes", false, []TestMessage{{null, general, "Ok, I'll replace the old one", false}, {bob, general, "What keywords or phrase .*", false}}, []bot.Event{}, 0},
			{bobID, general, "News for Nerds, Stuff that Matters!", false, []TestMessage{{null, general, "Link added", false}}, []bot.Event{}, 0},
			{carolID, general, "Bender, look up nerds", false, []TestMessage{{null, general, `(?s:Here's what I have .*Nerds.*)`, false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, ";link tuna casserole to https://www.allrecipes.com/recipe/17219/best-tuna-casserole/", false, []TestMessage{{null, general, `Link added`, false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, ";add it to the dinner meals list", false, []TestMessage{{alice, general, `I don't have a .*`, false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, "yes", false, []TestMessage{{null, general, `Ok, .*`, false}}, []bot.Event{}, 0},
			{aliceID, general, "Bender, look it up", false, []TestMessage{{null, general, `(?s:Here's what I have .*best.*)`, false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
			{aliceID, general, "add hamburgers to the list, bender", false, []TestMessage{{null, general, `Ok, I added hamburgers to the dinner meals list`, false}}, []bot.Event{bot.CommandTaskRan, bot.GoPluginRan}, 0},
		}),
	})
	Register(Suite{
		Name:      "TestExternalEncryptSecret",
		ConfigDir: "test/membrain",
		LogName:   "bottest.log",
		Cases: legacyRepliesOnlyCases([]testItem{
			{aliceID, general, ";python-encrypt-secret", false, []TestMessage{{null, general, "ENCRYPT SECRET: ok", false}}, nil, 0},
			{aliceID, general, ";python-encrypt-secret-unpriv", false, []TestMessage{{null, general, "ENCRYPT SECRET: failed", false}}, nil, 0},
			{aliceID, general, ";ruby-encrypt-secret", false, []TestMessage{{null, general, "ENCRYPT SECRET: ok", false}}, nil, 0},
			{aliceID, general, ";ruby-encrypt-secret-unpriv", false, []TestMessage{{null, general, "ENCRYPT SECRET: failed", false}}, nil, 0},
		}),
	})
	Register(Suite{
		Name:      "TestPythonSecurity",
		ConfigDir: "test/membrain",
		LogName:   "bottest.log",
		Cases: legacyRepliesOnlyCases([]testItem{
			{aliceID, general, ";python-sec-open", false, []TestMessage{{null, general, "SECURITY CHECK: secopen", false}}, nil, 0},
			{bobID, general, ";python-sec-open", false, []TestMessage{{null, general, "SECURITY CHECK: secopen", false}}, nil, 0},
			{aliceID, general, ";python-sec-admincmd", false, []TestMessage{{null, general, "SECURITY CHECK: secadmincmd", false}}, nil, 0},
			{bobID, general, ";python-sec-admincmd", false, []TestMessage{{null, general, "Sorry, 'pysec/secadmincmd' is only available to bot administrators", false}}, nil, 0},
			{bobID, general, ";python-sec-authz", false, []TestMessage{{null, general, "SECURITY CHECK: secauthz", false}}, nil, 0},
			{davidID, general, ";python-sec-authz", false, []TestMessage{{null, general, "Sorry, you're not authorized for that command", false}}, nil, 0},
			{bobID, general, ";python-sec-authall", false, []TestMessage{{null, general, "SECURITY CHECK: secauthall", false}}, nil, 0},
			{davidID, general, ";python-sec-authall", false, []TestMessage{{null, general, "Sorry, you're not authorized for that command", false}}, nil, 0},
			{aliceID, general, ";python-sec-elevated", false, []TestMessage{{alice, general, "This command requires.*elevation.*TOTP code.*", false}}, nil, 150},
			{aliceID, general, "123456", false, []TestMessage{{null, general, "There were technical issues validating your code.*", false}, {null, general, "Sorry, elevation failed due to a problem with the elevation service", false}}, nil, 0},
			{aliceID, general, ";python-sec-immediate", false, []TestMessage{{alice, general, "This command requires immediate elevation.*TOTP code.*", false}}, nil, 150},
			{aliceID, general, "123456", false, []TestMessage{{null, general, "There were technical issues validating your code.*", false}, {null, general, "Sorry, elevation failed due to a problem with the elevation service", false}}, nil, 0},
			{aliceID, general, "/bender: python-sec-hidden-ok", false, []TestMessage{{null, general, "\\(SECURITY CHECK: sechiddenok\\)", false}}, nil, 0},
			{aliceID, general, "/bender: python-sec-hidden-denied", false, []TestMessage{{alice, general, "\\(?Sorry, 'pysec/sechiddendenied' cannot be run as a hidden command - use the robot's name or alias\\)?", false}}, nil, 0},
			{aliceID, general, ";python-sec-adminonly", false, []TestMessage{{null, general, "SECURITY CHECK: secadminonly", false}}, nil, 0},
			{bobID, general, ";python-sec-adminonly", false, []TestMessage{{null, general, `(?s:I couldn't match .*Try .*commands.*help <keyword>.*)`, true}}, nil, 0},
			{aliceID, general, ";python-sec-usersonly", false, []TestMessage{{null, general, "SECURITY CHECK: secusersonly", false}}, nil, 0},
			{bobID, general, ";python-sec-usersonly", false, []TestMessage{{null, general, `(?s:I couldn't match .*Try .*commands.*help <keyword>.*)`, true}}, nil, 0},
			{aliceID, general, ";python-sec-auth-misconfig", false, []TestMessage{{null, general, `(?s:I couldn't match .*Try .*commands.*help <keyword>.*)`, true}}, nil, 0},
		}),
	})
}
