package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAttachmentsGetAttachmentInfoParams creates a new AttachmentsGetAttachmentInfoParams object
// with the default values initialized.
func NewAttachmentsGetAttachmentInfoParams() *AttachmentsGetAttachmentInfoParams {
	var ()
	return &AttachmentsGetAttachmentInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAttachmentsGetAttachmentInfoParamsWithTimeout creates a new AttachmentsGetAttachmentInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAttachmentsGetAttachmentInfoParamsWithTimeout(timeout time.Duration) *AttachmentsGetAttachmentInfoParams {
	var ()
	return &AttachmentsGetAttachmentInfoParams{

		timeout: timeout,
	}
}

// NewAttachmentsGetAttachmentInfoParamsWithContext creates a new AttachmentsGetAttachmentInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewAttachmentsGetAttachmentInfoParamsWithContext(ctx context.Context) *AttachmentsGetAttachmentInfoParams {
	var ()
	return &AttachmentsGetAttachmentInfoParams{

		Context: ctx,
	}
}

/*AttachmentsGetAttachmentInfoParams contains all the parameters to send to the API endpoint
for the attachments get attachment info operation typically these are written to a http.Request
*/
type AttachmentsGetAttachmentInfoParams struct {

	/*AttachmentID
	  attachment id

	*/
	AttachmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the attachments get attachment info params
func (o *AttachmentsGetAttachmentInfoParams) WithTimeout(timeout time.Duration) *AttachmentsGetAttachmentInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the attachments get attachment info params
func (o *AttachmentsGetAttachmentInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the attachments get attachment info params
func (o *AttachmentsGetAttachmentInfoParams) WithContext(ctx context.Context) *AttachmentsGetAttachmentInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the attachments get attachment info params
func (o *AttachmentsGetAttachmentInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAttachmentID adds the attachmentID to the attachments get attachment info params
func (o *AttachmentsGetAttachmentInfoParams) WithAttachmentID(attachmentID string) *AttachmentsGetAttachmentInfoParams {
	o.SetAttachmentID(attachmentID)
	return o
}

// SetAttachmentID adds the attachmentId to the attachments get attachment info params
func (o *AttachmentsGetAttachmentInfoParams) SetAttachmentID(attachmentID string) {
	o.AttachmentID = attachmentID
}

// WriteToRequest writes these params to a swagger request
func (o *AttachmentsGetAttachmentInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param attachmentId
	if err := r.SetPathParam("attachmentId", o.AttachmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
