package conversations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/uva-its/gopherbot/connectors/msteamchat/models"
)

// NewConversationsReplyToActivityParams creates a new ConversationsReplyToActivityParams object
// with the default values initialized.
func NewConversationsReplyToActivityParams() *ConversationsReplyToActivityParams {
	var ()
	return &ConversationsReplyToActivityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewConversationsReplyToActivityParamsWithTimeout creates a new ConversationsReplyToActivityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewConversationsReplyToActivityParamsWithTimeout(timeout time.Duration) *ConversationsReplyToActivityParams {
	var ()
	return &ConversationsReplyToActivityParams{

		timeout: timeout,
	}
}

// NewConversationsReplyToActivityParamsWithContext creates a new ConversationsReplyToActivityParams object
// with the default values initialized, and the ability to set a context for a request
func NewConversationsReplyToActivityParamsWithContext(ctx context.Context) *ConversationsReplyToActivityParams {
	var ()
	return &ConversationsReplyToActivityParams{

		Context: ctx,
	}
}

/*ConversationsReplyToActivityParams contains all the parameters to send to the API endpoint
for the conversations reply to activity operation typically these are written to a http.Request
*/
type ConversationsReplyToActivityParams struct {

	/*Activity
	  Activity to send

	*/
	Activity *models.Activity
	/*ActivityID
	  activityId the reply is to (OPTIONAL)

	*/
	ActivityID string
	/*ConversationID
	  Conversation ID

	*/
	ConversationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) WithTimeout(timeout time.Duration) *ConversationsReplyToActivityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) WithContext(ctx context.Context) *ConversationsReplyToActivityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithActivity adds the activity to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) WithActivity(activity *models.Activity) *ConversationsReplyToActivityParams {
	o.SetActivity(activity)
	return o
}

// SetActivity adds the activity to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) SetActivity(activity *models.Activity) {
	o.Activity = activity
}

// WithActivityID adds the activityID to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) WithActivityID(activityID string) *ConversationsReplyToActivityParams {
	o.SetActivityID(activityID)
	return o
}

// SetActivityID adds the activityId to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) SetActivityID(activityID string) {
	o.ActivityID = activityID
}

// WithConversationID adds the conversationID to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) WithConversationID(conversationID string) *ConversationsReplyToActivityParams {
	o.SetConversationID(conversationID)
	return o
}

// SetConversationID adds the conversationId to the conversations reply to activity params
func (o *ConversationsReplyToActivityParams) SetConversationID(conversationID string) {
	o.ConversationID = conversationID
}

// WriteToRequest writes these params to a swagger request
func (o *ConversationsReplyToActivityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Activity == nil {
		o.Activity = new(models.Activity)
	}

	if err := r.SetBodyParam(o.Activity); err != nil {
		return err
	}

	// path param activityId
	if err := r.SetPathParam("activityId", o.ActivityID); err != nil {
		return err
	}

	// path param conversationId
	if err := r.SetPathParam("conversationId", o.ConversationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
