package conversations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/uva-its/gopherbot/connectors/msteamchat/models"
)

// ConversationsGetConversationMembersReader is a Reader for the ConversationsGetConversationMembers structure.
type ConversationsGetConversationMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConversationsGetConversationMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewConversationsGetConversationMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewConversationsGetConversationMembersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewConversationsGetConversationMembersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewConversationsGetConversationMembersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewConversationsGetConversationMembersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewConversationsGetConversationMembersMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewConversationsGetConversationMembersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewConversationsGetConversationMembersServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewConversationsGetConversationMembersOK creates a ConversationsGetConversationMembersOK with default headers values
func NewConversationsGetConversationMembersOK() *ConversationsGetConversationMembersOK {
	return &ConversationsGetConversationMembersOK{}
}

/*ConversationsGetConversationMembersOK handles this case with default header values.

An array of ChannelAccount objects
*/
type ConversationsGetConversationMembersOK struct {
	Payload []*models.ChannelAccount
}

func (o *ConversationsGetConversationMembersOK) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersOK  %+v", 200, o.Payload)
}

func (o *ConversationsGetConversationMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConversationsGetConversationMembersBadRequest creates a ConversationsGetConversationMembersBadRequest with default headers values
func NewConversationsGetConversationMembersBadRequest() *ConversationsGetConversationMembersBadRequest {
	return &ConversationsGetConversationMembersBadRequest{}
}

/*ConversationsGetConversationMembersBadRequest handles this case with default header values.

The request was malformed or otherwise incorrect. Inspect the message for a more detailed description.
*/
type ConversationsGetConversationMembersBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *ConversationsGetConversationMembersBadRequest) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersBadRequest  %+v", 400, o.Payload)
}

func (o *ConversationsGetConversationMembersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConversationsGetConversationMembersUnauthorized creates a ConversationsGetConversationMembersUnauthorized with default headers values
func NewConversationsGetConversationMembersUnauthorized() *ConversationsGetConversationMembersUnauthorized {
	return &ConversationsGetConversationMembersUnauthorized{}
}

/*ConversationsGetConversationMembersUnauthorized handles this case with default header values.

The bot is not authorized to make this request. Please check your Microsoft App ID and Microsoft App password.
*/
type ConversationsGetConversationMembersUnauthorized struct {
}

func (o *ConversationsGetConversationMembersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersUnauthorized ", 401)
}

func (o *ConversationsGetConversationMembersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewConversationsGetConversationMembersForbidden creates a ConversationsGetConversationMembersForbidden with default headers values
func NewConversationsGetConversationMembersForbidden() *ConversationsGetConversationMembersForbidden {
	return &ConversationsGetConversationMembersForbidden{}
}

/*ConversationsGetConversationMembersForbidden handles this case with default header values.

The request was a valid request, but the server is refusing to respond to it. The user might be logged in but does not have the necessary permissions for the resource.
*/
type ConversationsGetConversationMembersForbidden struct {
}

func (o *ConversationsGetConversationMembersForbidden) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersForbidden ", 403)
}

func (o *ConversationsGetConversationMembersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewConversationsGetConversationMembersNotFound creates a ConversationsGetConversationMembersNotFound with default headers values
func NewConversationsGetConversationMembersNotFound() *ConversationsGetConversationMembersNotFound {
	return &ConversationsGetConversationMembersNotFound{}
}

/*ConversationsGetConversationMembersNotFound handles this case with default header values.

The resource was not found.
*/
type ConversationsGetConversationMembersNotFound struct {
	Payload *models.ErrorResponse
}

func (o *ConversationsGetConversationMembersNotFound) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersNotFound  %+v", 404, o.Payload)
}

func (o *ConversationsGetConversationMembersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConversationsGetConversationMembersMethodNotAllowed creates a ConversationsGetConversationMembersMethodNotAllowed with default headers values
func NewConversationsGetConversationMembersMethodNotAllowed() *ConversationsGetConversationMembersMethodNotAllowed {
	return &ConversationsGetConversationMembersMethodNotAllowed{}
}

/*ConversationsGetConversationMembersMethodNotAllowed handles this case with default header values.

The method and URI you are trying to use is not allowed on this service.  For example, not all services support the DELETE or PUT verbs on an activity URI.
*/
type ConversationsGetConversationMembersMethodNotAllowed struct {
	Payload *models.ErrorResponse
}

func (o *ConversationsGetConversationMembersMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *ConversationsGetConversationMembersMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConversationsGetConversationMembersInternalServerError creates a ConversationsGetConversationMembersInternalServerError with default headers values
func NewConversationsGetConversationMembersInternalServerError() *ConversationsGetConversationMembersInternalServerError {
	return &ConversationsGetConversationMembersInternalServerError{}
}

/*ConversationsGetConversationMembersInternalServerError handles this case with default header values.

An internal server has occurred. Inspect the message for a more detailed description.
*/
type ConversationsGetConversationMembersInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ConversationsGetConversationMembersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersInternalServerError  %+v", 500, o.Payload)
}

func (o *ConversationsGetConversationMembersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConversationsGetConversationMembersServiceUnavailable creates a ConversationsGetConversationMembersServiceUnavailable with default headers values
func NewConversationsGetConversationMembersServiceUnavailable() *ConversationsGetConversationMembersServiceUnavailable {
	return &ConversationsGetConversationMembersServiceUnavailable{}
}

/*ConversationsGetConversationMembersServiceUnavailable handles this case with default header values.

The service you are trying to communciate with is unavailable.
*/
type ConversationsGetConversationMembersServiceUnavailable struct {
	Payload *models.ErrorResponse
}

func (o *ConversationsGetConversationMembersServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /v3/conversations/{conversationId}/members][%d] conversationsGetConversationMembersServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ConversationsGetConversationMembersServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
