ARG base_org=lnxjedi

FROM ghcr.io/${base_org}/gopherbot-base:latest

#######
# containerfile.dev
# For daily builds of a gopherbot development container with up-to-date sources.
#######

ARG USERNAME=bot

WORKDIR /home/${USERNAME}
RUN curl -o .git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash && \
    curl -o .git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

COPY --chown=${USERNAME}:${USERNAME} tmp/gopherbot/ /opt/gopherbot/
COPY --chown=${USERNAME}:${USERNAME} tmp/gopherbot-doc/ /opt/gopherbot-doc/
COPY --chown=${USERNAME}:${USERNAME} assets/gopherbot.code-workspace /home/${USERNAME}/gopherbot.code-workspace
COPY --chown=${USERNAME}:${USERNAME} assets/dev-init /home/${USERNAME}/.dev-init
COPY --chown=${USERNAME}:${USERNAME} assets/gitconfig /home/${USERNAME}/.gitconfig

RUN echo "source /home/${USERNAME}/.dev-init" >> /home/${USERNAME}/.bashrc && \
    mkdir -p /home/${USERNAME}/.ssh && \
    chmod 0700 /home/${USERNAME}/.ssh && \
    cd /opt/gopherbot-doc && \
    sed -i -e '/\[http/,+1d' .git/config && \
    cd /opt/gopherbot && \
    sed -i -e '/\[http/,+1d' .git/config && \
    make

ENV RUBYLIB=/opt/gopherbot/lib:/home/${USERNAME}/custom/lib \
    PYTHONPATH=/opt/gopherbot/lib:/home/${USERNAME}/custom/lib \
    GOPHER_INSTALLDIR=/opt/gopherbot \
    GOPHER_IDE=true

ENTRYPOINT [ "/usr/bin/tini", "--", "/usr/bin/ssh-agent", "/bin/sh", "-c", "exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server --host 0.0.0.0 --port 7777 \"${@}\"", "--" ]
