FROM quay.io/lnxjedi/gopherbot-base-theia:latest

USER root

ADD gopherbot-linux-amd64.tar.gz /opt

RUN chown nobody /opt/gopherbot/gopherbot && \
  chmod u+s /opt/gopherbot/gopherbot

WORKDIR ${HOME}

# Numeric for Kubernetes runAsNonRoot
USER ${ROBOT_UID}:${ROBOT_UID}

EXPOSE 3000
# In the gopherbot-theia image, theia runs as a gopherbot job
ENTRYPOINT [ "/opt/gopherbot/gopherbot" , "-plainlog" ]
