FROM quay.io/lnxjedi/gopherbot-base-theia:latest

USER root

ARG buildref
ENV BUILDREF=${buildref}

RUN cd / && \
  [ "$BUILDREF" ] && CLONEREF="-b $BUILDREF" || : && \
  git clone ${CLONEREF} https://github.com/lnxjedi/gopherbot.git build && \
  cd build && \
  make dist && \
  cd /opt && \
  tar xzf /build/gopherbot-linux-amd64.tar.gz && \
  rm -rf /build /root/.cache && \
  chown nobody /opt/gopherbot/gopherbot && \
  chmod u+s /opt/gopherbot/gopherbot

ENV PATH=/opt/gopherbot:${PATH}

RUN adduser -u 1000 \
    --no-create-home \
    --disabled-password \
    --gecos '' robot && \
  mkdir /home/robot && \
  chown robot:robot /home/robot && \
  chmod 0755 /home/robot

COPY --chown=robot:robot robot-bashrc /home/robot/.bashrc

# Numeric for Kubernetes runAsNonRoot
USER 1000:robot
ENV GOPATH=/home/robot
RUN ln -s /opt/gopherbot /home/robot/robot-defaults && \
  mkdir /home/robot/bin

WORKDIR /home/robot

EXPOSE 3000
# In the gopherbot-theia image, theia runs as a gopherbot job
ENTRYPOINT [ "/opt/gopherbot/gopherbot" , "-plainlog" ]
