// Code generated by "stringer -type=pipeAddFlavor constants.go"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[flavorSpawn-0]
	_ = x[flavorAdd-1]
	_ = x[flavorFinal-2]
	_ = x[flavorFail-3]
}

const _pipeAddFlavor_name = "flavorSpawnflavorAddflavorFinalflavorFail"

var _pipeAddFlavor_index = [...]uint8{0, 11, 20, 31, 41}

func (i pipeAddFlavor) String() string {
	if i < 0 || i >= pipeAddFlavor(len(_pipeAddFlavor_index)-1) {
		return "pipeAddFlavor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pipeAddFlavor_name[_pipeAddFlavor_index[i]:_pipeAddFlavor_index[i+1]]
}
