// Code generated by "stringer -type=pipelineType constants.go"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[plugCommand-0]
	_ = x[plugMessage-1]
	_ = x[catchAll-2]
	_ = x[jobTrigger-3]
	_ = x[spawnedTask-4]
	_ = x[scheduled-5]
	_ = x[jobCmd-6]
	_ = x[pipeAdd-7]
}

const _pipelineType_name = "plugCommandplugMessagecatchAlljobTriggerspawnedTaskscheduledjobCmdpipeAdd"

var _pipelineType_index = [...]uint8{0, 11, 22, 30, 40, 51, 60, 66, 73}

func (i pipelineType) String() string {
	if i < 0 || i >= pipelineType(len(_pipelineType_index)-1) {
		return "pipelineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pipelineType_name[_pipelineType_index[i]:_pipelineType_index[i+1]]
}
