// Code generated by "stringer -type=pipeAddFlavor constants.go"; DO NOT EDIT.

package bot

import "strconv"

const _pipeAddFlavor_name = "flavorSpawnflavorAddflavorFinalflavorFail"

var _pipeAddFlavor_index = [...]uint8{0, 11, 20, 31, 41}

func (i pipeAddFlavor) String() string {
	if i < 0 || i >= pipeAddFlavor(len(_pipeAddFlavor_index)-1) {
		return "pipeAddFlavor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pipeAddFlavor_name[_pipeAddFlavor_index[i]:_pipeAddFlavor_index[i+1]]
}
