// Code generated by "stringer -type=TaskRetVal"; DO NOT EDIT.

package bot

import "strconv"

const _TaskRetVal_name = "NormalFailMechanismFailConfigurationError"

var _TaskRetVal_index = [...]uint8{0, 6, 10, 23, 41}

func (i TaskRetVal) String() string {
	if i < 0 || i >= TaskRetVal(len(_TaskRetVal_index)-1) {
		return "TaskRetVal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskRetVal_name[_TaskRetVal_index[i]:_TaskRetVal_index[i+1]]
}
