// Code generated by "stringer -type=taskType constants.go"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[taskGo-0]
	_ = x[taskExternal-1]
}

const _taskType_name = "taskGotaskExternal"

var _taskType_index = [...]uint8{0, 6, 18}

func (i taskType) String() string {
	if i < 0 || i >= taskType(len(_taskType_index)-1) {
		return "taskType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _taskType_name[_taskType_index[i]:_taskType_index[i+1]]
}
