// Code generated by "stringer -type=taskType constants.go"; DO NOT EDIT.

package bot

import "strconv"

const _taskType_name = "taskGotaskExternal"

var _taskType_index = [...]uint8{0, 6, 18}

func (i taskType) String() string {
	if i < 0 || i >= taskType(len(_taskType_index)-1) {
		return "taskType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _taskType_name[_taskType_index[i]:_taskType_index[i+1]]
}
