package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// AttachmentView Attachment View name and size
// swagger:model AttachmentView
type AttachmentView struct {

	// Name of the attachment
	Size int32 `json:"size,omitempty"`

	// content type of the attachmnet
	ViewID string `json:"viewId,omitempty"`
}

// Validate validates this attachment view
func (m *AttachmentView) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
