package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Attachment An attachment within an activity
// swagger:model Attachment
type Attachment struct {

	// Embedded content
	Content Object `json:"content,omitempty"`

	// mimetype/Contenttype for the file
	ContentType string `json:"contentType,omitempty"`

	// Content Url
	ContentURL string `json:"contentUrl,omitempty"`

	// (OPTIONAL) The name of the attachment
	Name string `json:"name,omitempty"`

	// (OPTIONAL) Thumbnail associated with attachment
	ThumbnailURL string `json:"thumbnailUrl,omitempty"`
}

// Validate validates this attachment
func (m *Attachment) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
