package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// AttachmentInfo Metdata for an attachment
// swagger:model AttachmentInfo
type AttachmentInfo struct {

	// Name of the attachment
	Name string `json:"name,omitempty"`

	// ContentType of the attachment
	Type string `json:"type,omitempty"`

	// attachment views
	Views []*AttachmentView `json:"views"`
}

// Validate validates this attachment info
func (m *AttachmentInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateViews(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AttachmentInfo) validateViews(formats strfmt.Registry) error {

	if swag.IsZero(m.Views) { // not required
		return nil
	}

	for i := 0; i < len(m.Views); i++ {

		if swag.IsZero(m.Views[i]) { // not required
			continue
		}

		if m.Views[i] != nil {

			if err := m.Views[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
