package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// CardImage An image on a card
// swagger:model CardImage
type CardImage struct {

	// Image description intended for screen readers
	Alt string `json:"alt,omitempty"`

	// Action assigned to specific Attachment.E.g.navigate to specific URL or play/open media content
	Tap *CardAction `json:"tap,omitempty"`

	// URL Thumbnail image for major content property.
	URL string `json:"url,omitempty"`
}

// Validate validates this card image
func (m *CardImage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTap(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CardImage) validateTap(formats strfmt.Registry) error {

	if swag.IsZero(m.Tap) { // not required
		return nil
	}

	if m.Tap != nil {

		if err := m.Tap.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
