package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ChannelAccount Channel account information needed to route a message
// swagger:model ChannelAccount
type ChannelAccount struct {

	// Channel id for the user or bot on this channel (Example: joe@smith.com, or @joesmith or 123456)
	ID string `json:"id,omitempty"`

	// Display friendly name
	Name string `json:"name,omitempty"`
}

// Validate validates this channel account
func (m *ChannelAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
