package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ConversationAccount Channel account information for a conversation
// swagger:model ConversationAccount
type ConversationAccount struct {

	// Channel id for the user or bot on this channel (Example: joe@smith.com, or @joesmith or 123456)
	ID string `json:"id,omitempty"`

	// Is this a reference to a group
	IsGroup bool `json:"isGroup,omitempty"`

	// Display friendly name
	Name string `json:"name,omitempty"`
}

// Validate validates this conversation account
func (m *ConversationAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
