package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ConversationResourceResponse A response containing a resource
// swagger:model ConversationResourceResponse
type ConversationResourceResponse struct {

	// Id of the Activity (if one was created)
	ActivityID string `json:"activityId,omitempty"`

	// Id of the resource
	ID string `json:"id,omitempty"`
}

// Validate validates this conversation resource response
func (m *ConversationResourceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
