package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Fact Set of key-value pairs. Advantage of this section is that key and value properties will be
//             rendered with default style information with some delimiter between them. So there is no need for developer to specify style information.
// swagger:model Fact
type Fact struct {

	// The key for this Fact
	Key string `json:"key,omitempty"`

	// The value for this Fact
	Value string `json:"value,omitempty"`
}

// Validate validates this fact
func (m *Fact) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
