package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// GeoCoordinates GeoCoordinates (entity type: "https://schema.org/GeoCoordinates")
// swagger:model GeoCoordinates
type GeoCoordinates struct {

	// Elevation of the location [WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)
	Elevation float64 `json:"elevation,omitempty"`

	// Latitude of the location [WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)
	Latitude float64 `json:"latitude,omitempty"`

	// Longitude of the location [WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)
	Longitude float64 `json:"longitude,omitempty"`

	// The name of the thing
	Name string `json:"name,omitempty"`

	// The type of the thing
	Type string `json:"type,omitempty"`
}

// Validate validates this geo coordinates
func (m *GeoCoordinates) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
