package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ReceiptCard A receipt card
// swagger:model ReceiptCard
type ReceiptCard struct {

	// Set of actions applicable to the current card
	Buttons []*CardAction `json:"buttons"`

	// Array of Fact Objects   Array of key-value pairs.
	Facts []*Fact `json:"facts"`

	// Array of Receipt Items
	Items []*ReceiptItem `json:"items"`

	// This action will be activated when user taps on the card
	Tap *CardAction `json:"tap,omitempty"`

	// Total amount of TAX paid(or should be paid)
	Tax string `json:"tax,omitempty"`

	// Title of the card
	Title string `json:"title,omitempty"`

	// Total amount of money paid (or should be paid)
	Total string `json:"total,omitempty"`

	// Total amount of VAT paid(or should be paid)
	Vat string `json:"vat,omitempty"`
}

// Validate validates this receipt card
func (m *ReceiptCard) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateButtons(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateFacts(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateItems(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTap(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReceiptCard) validateButtons(formats strfmt.Registry) error {

	if swag.IsZero(m.Buttons) { // not required
		return nil
	}

	for i := 0; i < len(m.Buttons); i++ {

		if swag.IsZero(m.Buttons[i]) { // not required
			continue
		}

		if m.Buttons[i] != nil {

			if err := m.Buttons[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ReceiptCard) validateFacts(formats strfmt.Registry) error {

	if swag.IsZero(m.Facts) { // not required
		return nil
	}

	for i := 0; i < len(m.Facts); i++ {

		if swag.IsZero(m.Facts[i]) { // not required
			continue
		}

		if m.Facts[i] != nil {

			if err := m.Facts[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ReceiptCard) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(m.Items) { // not required
		return nil
	}

	for i := 0; i < len(m.Items); i++ {

		if swag.IsZero(m.Items[i]) { // not required
			continue
		}

		if m.Items[i] != nil {

			if err := m.Items[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ReceiptCard) validateTap(formats strfmt.Registry) error {

	if swag.IsZero(m.Tap) { // not required
		return nil
	}

	if m.Tap != nil {

		if err := m.Tap.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
