package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// SigninCard A card representing a request to sign in
// swagger:model SigninCard
type SigninCard struct {

	// Action to use to perform signin
	Buttons []*CardAction `json:"buttons"`

	// Text for signin request
	Text string `json:"text,omitempty"`
}

// Validate validates this signin card
func (m *SigninCard) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateButtons(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SigninCard) validateButtons(formats strfmt.Registry) error {

	if swag.IsZero(m.Buttons) { // not required
		return nil
	}

	for i := 0; i < len(m.Buttons); i++ {

		if swag.IsZero(m.Buttons[i]) { // not required
			continue
		}

		if m.Buttons[i] != nil {

			if err := m.Buttons[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
