apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gopherbot.fullname" . }}
  labels:
    {{- include "gopherbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gopherbot.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "gopherbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GOPHER_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.robotName | default "robot" }}-secrets
                  key: GOPHER_ENCRYPTION_KEY
            - name: GOPHER_CUSTOM_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.robotName | default "robot" }}-secrets
                  key: GOPHER_CUSTOM_REPOSITORY
            - name: GOPHER_DEPLOY_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.robotName | default "robot" }}-secrets
                  key: GOPHER_DEPLOY_KEY
            - name: GOPHER_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.robotName | default "robot" }}-secrets
                  key: GOPHER_PROTOCOL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
