apiVersion: v1
data:
  GOPHER_CUSTOM_REPOSITORY: {{ default "" .Values.robotRepository | b64enc }}
  GOPHER_DEPLOY_KEY: {{ default "" .Values.deployKey | b64enc }}
  GOPHER_ENCRYPTION_KEY: {{ default "" .Values.encryptionKey | b64enc }}
  GOPHER_PROTOCOL: {{ default "" .Values.protocol | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.robotName }}-secrets
