package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/uva-its/gopherbot/connectors/msteamchat/client/attachments"
	"github.com/uva-its/gopherbot/connectors/msteamchat/client/conversations"
)

// Default microsoft bot connector API v30 HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new microsoft bot connector API v30 HTTP client.
func NewHTTPClient(formats strfmt.Registry) *MicrosoftBotConnectorAPIV30 {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("api.botframework.com", "/", []string{"https"})
	return New(transport, formats)
}

// New creates a new microsoft bot connector API v30 client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *MicrosoftBotConnectorAPIV30 {
	cli := new(MicrosoftBotConnectorAPIV30)
	cli.Transport = transport

	cli.Attachments = attachments.New(transport, formats)

	cli.Conversations = conversations.New(transport, formats)

	return cli
}

// MicrosoftBotConnectorAPIV30 is a client for microsoft bot connector API v30
type MicrosoftBotConnectorAPIV30 struct {
	Attachments *attachments.Client

	Conversations *conversations.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *MicrosoftBotConnectorAPIV30) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Attachments.SetTransport(transport)

	c.Conversations.SetTransport(transport)

}
